
spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://34.95.177.62/cerebro
spring.datasource.url=jdbc:postgresql://ec2-52-0-155-79.compute-1.amazonaws.com:5432/d32g52qdf6i1si
#spring.datasource.username=cerebro
spring.datasource.username=qjrjldiefeuddl
#spring.datasource.password=cerebro
spring.datasource.password=30d7d1b40fa702793f67b3c4a76631a7d0f51667742ad49ba00d1c523f80d1e0
server.port=8081
server.error.include-stacktrace=never


#spring.cloud.gcp.sql.database-name=cerebro
#spring.cloud.gcp.sql.instance-connection-name=cerebro-281813:southamerica-east1:cerebro123

# So app starts despite "table already exists" errors.
spring.datasource.continue-on-error=true
# Enforces database initialization
spring.datasource.initialization-mode=always
#spring.cloud.gcp.project-id=cerebro-281813
#spring.cloud.gcp.credentials.location=file:/src/main/resources/cerebro-281813-33180cf98e8a.json